.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH plugin-inspect 1  "plugin-inspect " 
.SH NAME
plugin\-inspect \- Inspect a specific plugin\*(Aqs capabilities and metadata
.SH SYNOPSIS
\fBplugin\-inspect\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Inspect a specific plugin\*(Aqs capabilities and metadata
.SH OPTIONS
.TP
\fB\-\-format\fR \fI<FORMAT>\fR [default: pretty]
Output format (pretty, json)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
pretty
.IP \(bu 2
json
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Name of the plugin to inspect
