.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH profile 1  "profile " 
.SH NAME
profile \- Profile a single function execution and print hotspots + suggestions
.SH SYNOPSIS
\fBprofile\fR <\fB\-c\fR|\fB\-\-contract\fR> <\fB\-f\fR|\fB\-\-function\fR> [\fB\-a\fR|\fB\-\-args\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-s\fR|\fB\-\-storage\fR] [\fB\-\-expected\-hash\fR] [\fB\-\-flamegraph\fR] [\fB\-\-flamegraph\-stacks\fR] [\fB\-\-flamegraph\-width\fR] [\fB\-\-flamegraph\-height\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Profile a single function execution and print hotspots + suggestions. Optionally generate flame graph artifacts for performance visualization.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-contract\fR \fI<CONTRACT>\fR
Path to the contract WASM file
.TP
\fB\-f\fR, \fB\-\-function\fR \fI<FUNCTION>\fR
Function name to execute
.TP
\fB\-a\fR, \fB\-\-args\fR \fI<ARGS>\fR
Function arguments as JSON array (e.g., \*(Aq["arg1", "arg2"]\*(Aq)
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<OUTPUT>\fR
Output file for the profile report (default: stdout)
.TP
\fB\-s\fR, \fB\-\-storage\fR \fI<STORAGE>\fR
Initial storage state as JSON object
.TP
\fB\-\-expected\-hash\fR \fI<EXPECTED_HASH>\fR
Expected SHA\-256 hash of the WASM file. If provided, loading will fail if the computed hash does not match
.TP
\fB\-\-flamegraph\fR \fI<FLAMEGRAPH>\fR
Export flame graph as SVG file for visualization
.TP
\fB\-\-flamegraph\-stacks\fR \fI<FLAMEGRAPH_STACKS>\fR
Export collapsed stack format (intermediate format compatible with Flamegraph tools)
.TP
\fB\-\-flamegraph\-width\fR \fI<WIDTH>\fR
Width for flame graph SVG rendering in pixels (default: 1200)
.TP
\fB\-\-flamegraph\-height\fR \fI<HEIGHT>\fR
Height for flame graph SVG rendering in pixels (default: 800)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
