.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH symbolic 1  "symbolic " 
.SH NAME
symbolic \- Run symbolic execution to explore contract input space
.SH SYNOPSIS
\fBsymbolic\fR <\fB\-c\fR|\fB\-\-contract\fR> <\fB\-f\fR|\fB\-\-function\fR> [\fB\-o\fR|\fB\-\-output\fR] [\fB\-\-profile\fR] [\fB\-\-input\-combination\-cap\fR] [\fB\-\-path\-cap\fR] [\fB\-\-timeout\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Run symbolic execution to explore contract input space
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-contract\fR \fI<CONTRACT>\fR
Path to the contract WASM file
.TP
\fB\-f\fR, \fB\-\-function\fR \fI<FUNCTION>\fR
Function name to execute
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<OUTPUT>\fR
Output file for the scenario TOML
.TP
\fB\-\-profile\fR \fI<PROFILE>\fR [default: balanced]
Preset symbolic exploration budget profile
.br

.br
[\fIpossible values: \fRfast, balanced, deep]
.TP
\fB\-\-input\-combination\-cap\fR \fI<N>\fR
Maximum number of input combinations to generate deterministically
.TP
\fB\-\-path\-cap\fR \fI<N>\fR
Maximum number of generated inputs to execute
.TP
\fB\-\-timeout\fR \fI<SECONDS>\fR
Overall symbolic analysis timeout in seconds
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
