.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH completions 1  "completions " 
.SH NAME
completions \- Generate shell completion scripts
.SH SYNOPSIS
\fBcompletions\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISHELL\fR> 
.SH DESCRIPTION
Generate shell completion scripts
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISHELL\fR>
Shell to generate completion script for
.br

.br
[\fIpossible values: \fRbash, elvish, fish, powershell, zsh]
