.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH inspect 1  "inspect " 
.SH NAME
inspect \- Inspect current execution state (function, step count, call stack)
.SH SYNOPSIS
\fBinspect\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Inspect current execution state (function, step count, call stack)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
